{% set data = load_setup_py_data() %}

package:
    name: sanipy
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

build:
  noarch: python
  entry_points:
    - sanipy = sani:main

requirements:
    build:
        - python >=3.6
        - setuptools
    run:
        - python >=3.6
        - pyepics
        - colorama
        - numpy
        - pandas


